M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-09-12T16:53:37-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T16:53:37-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
%
G90
G05
T1
X64.0Y-22.5
X64.0Y-36.5
X100.0Y-22.5
X100.0Y-36.5
T2
X22.3Y-22.3
X22.3Y-100.7
X28.5Y-28.0
X28.5Y-43.0
X127.7Y-22.3
X127.7Y-100.7
T3
X32.8Y-73.86
X56.8Y-73.86
M30
