M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-09-11T21:04:36-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-11T21:04:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X43.0Y-23.0
X43.0Y-37.0
X79.0Y-23.0
X79.0Y-37.0
T2
X26.0Y-42.0
X41.0Y-42.0
T3
X23.5Y-23.5
X23.5Y-78.5
X196.5Y-23.5
X196.5Y-78.5
T4
X162.7Y-32.0
X162.7Y-62.0
M30
